import { configDotenv } from "dotenv";
import { connectToDatabase, closeDatabaseConnection } from "../config/mongoConnection.js";
import { ObjectId } from "mongodb";
import {
    DISABILITY_CATEGORY_NEURODIVERGENT as NEURODIVERGENT,
    DISABILITY_CATEGORY_SENSORY as SENSORY,
    DISABILITY_CATEGORY_PHYSICAL as PHYSICAL
} from "../data/places.js";
import { DateTime } from "luxon"
import bcrypt from "bcrypt";
import { BCRYPT_SALT_ROUNDS } from "../data/user.js";
import { OSM_TYPE_NODE, OSM_TYPE_RELATION, OSM_TYPE_WAY } from "../data/geolocation.js";

configDotenv({ path: "../.env" });

/*
Timestamps generated by random.org. Numbers generated by shuf.
2611  2014-01-10T15:30:00.000-02:00
6593  2015-06-10T17:10:00.000-06:00
5711  2015-12-30T17:40:00.000-05:00
5567  2018-05-23T18:30:00.000-05:00
4377  2023-02-28T21:00:00.000-04:00
6594  2023-12-07T22:40:00.000-06:00
 */

// Data has been pseudorandomly generated or otherwise derived from public information. Names are
// pulled from the most common names by year in the US. Places were "randomly" chosen by us.

const users = {
    mildred: {
        _id: new ObjectId(),
        username: "mildred6603",
        hashedPassword: bcrypt.hashSync("sunimHJSWW3045_!&>", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("1993-05-10T00:10:00.000-06:00"),
        qualifications: [NEURODIVERGENT],
    },
    roger: {
        _id: new ObjectId(),
        username: "roger1945",
        hashedPassword: bcrypt.hashSync("cxkbvMTCQB5043/?.;", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("1993-09-03T00:20:00.000-01:00"),
        qualifications: [SENSORY, PHYSICAL],
    },
    samuel: {
        _id: new ObjectId(),
        username: "samuel5215",
        hashedPassword: bcrypt.hashSync("tnewrJORBS2464!@=&", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("1997-07-04T02:00:00.000-05:00"),
        qualifications: [NEURODIVERGENT, SENSORY],
    },
    william: {
        _id: new ObjectId(),
        username: "william6342",
        hashedPassword: bcrypt.hashSync("uvebvFXLKH6301^%>)", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("1998-10-09T02:20:00.000-06:00"),
        qualifications: [],
    },
    paul: {
        _id: new ObjectId(),
        username: "paul3497",
        hashedPassword: bcrypt.hashSync("kggohPSLLM4825^:@^", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2000-02-24T02:50:00.000-03:00"),
        qualifications: [NEURODIVERGENT],
    },
    rachel: {
        _id: new ObjectId(),
        username: "rachel5472",
        hashedPassword: bcrypt.hashSync("vbtqtOBYVY5708&,#:", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2001-09-04T04:00:00.000-05:00"),
        qualifications: [NEURODIVERGENT, SENSORY],
    },
    timothy: {
        _id: new ObjectId(),
        username: "timothy7857",
        hashedPassword: bcrypt.hashSync("", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2003-02-24T04:40:00.000-07:00"),
        qualifications: [SENSORY],
    },
    linda: {
        _id: new ObjectId(),
        username: "linda2054",
        hashedPassword: bcrypt.hashSync("ukyxtHTKRE8226=@+;", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2004-02-25T05:20:00.000-02:00"),
        qualifications: [],
    },
    katherine: {
        _id: new ObjectId(),
        username: "katherine2316",
        hashedPassword: bcrypt.hashSync("hbrvlDVUQY5810.,%)", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2006-07-25T05:30:00.000-02:00"),
        qualifications: [PHYSICAL],
    },
    rose: {
        _id: new ObjectId(),
        username: "rose7148",
        hashedPassword: bcrypt.hashSync("kdbapFXEKB5556/?):", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2006-08-07T09:50:00.000-07:00"),
        qualifications: [],
    },
    douglas: {
        _id: new ObjectId(),
        username: "douglas3405",
        hashedPassword: bcrypt.hashSync("rqisiWUTIX7626(%#<", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2007-09-26T10:00:00.000-03:00"),
        qualifications: [],
    },
    gregory: {
        _id: new ObjectId(),
        username: "gregory9034",
        hashedPassword: bcrypt.hashSync("mjwoaMMFLL6705>&(>", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2009-01-22T10:10:00.000-09:00"),
        qualifications: [NEURODIVERGENT, PHYSICAL],
    },
    sean: {
        _id: new ObjectId(),
        username: "sean3142",
        hashedPassword: bcrypt.hashSync("uttclPITGS8207,;,*", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2009-05-01T10:20:00.000-03:00"),
        qualifications: [PHYSICAL, SENSORY, NEURODIVERGENT],
    },
    aaron: {
        _id: new ObjectId(),
        username: "aaron8618",
        hashedPassword: bcrypt.hashSync("sovmcXRRUA5440:;!)", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2009-05-25T10:30:00.000-08:00"),
        qualifications: [],
    },
    joan: {
        _id: new ObjectId(),
        username: "joan4822",
        hashedPassword: bcrypt.hashSync("ykburRHQHI7586^&%-", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2010-02-24T12:10:00.000-04:00"),
        qualifications: [],
    },
    kyle: {
        _id: new ObjectId(),
        username: "kyle8306",
        hashedPassword: bcrypt.hashSync("nvtafUNXSJ7553!^$*", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2010-09-10T12:20:00.000-08:00\n"),
        qualifications: [],
    },
    janet: {
        _id: new ObjectId(),
        username: "janet4090",
        hashedPassword: bcrypt.hashSync("kfyfjENNCG3522/#?;", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2011-05-30T12:30:00.000-04:00"),
        qualifications: [],
    },
    logan: {
        _id: new ObjectId(),
        username: "logan8982",
        hashedPassword: bcrypt.hashSync("cqfooTIBHT8120(*?#", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2012-02-03T12:50:00.000-08:00"),
        qualifications: [],
    },
    christian: {
        _id: new ObjectId(),
        username: "christian5469",
        hashedPassword: bcrypt.hashSync("gvummJGJPU7571;-$_", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2013-10-16T13:00:00.000-05:00"),
        qualifications: [],
    },
    steven: {
        _id: new ObjectId(),
        username: "steven2611",
        hashedPassword: bcrypt.hashSync("pgwvyBWHTN2502%+*(", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2014-01-10T15:30:00.000-02:00"),
        qualifications: [SENSORY, NEURODIVERGENT],
    },
    lawrence: {
        _id: new ObjectId(),
        username: "lawrence2611",
        hashedPassword: bcrypt.hashSync("egtmfITIQF1621*<*>", BCRYPT_SALT_ROUNDS),
        createdAt: DateTime.fromISO("2014-01-10T15:30:00.000-02:00"),
        qualifications: [NEURODIVERGENT, SENSORY, PHYSICAL],
    }
};

const places = {
    stevens: {
        _id: new ObjectId(),
        name: "Stevens Institute of Technology",
        description: "Stevens Institute of Technology: The College",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "27080296",
            osmType: OSM_TYPE_WAY,
            address: "Stevens Institute of Technology, Castle Point Terrace, Uptown, Hoboken, Hudson County, New Jersey, 07030, United States",
            latitude: 40.744809599999996,
            longitude: -74.0252392276461,
        },
        reviews: [],
    },
    stevensHoweCenter: {
        _id: new ObjectId(),
        name: "Wesley J. Howe Center",
        description: "The Wesley J. Howe Center administrative building at Stevens Institute of Technology",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "26974143",
            osmType: OSM_TYPE_WAY,
            address: "Wesley J. Howe Center, 1, Wittpenn Walk, Uptown, Hoboken, Hudson County, New Jersey, 07030, United States",
            latitude: 40.7448047,
            longitude: -74.02386051290601,
        },
        reviews: [],
    },
    hobokenHospital: {
        _id: new ObjectId(),
        name: "Hoboken University Medical Center",
        description: "Hoboken University Medical Center: The Medical Center",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "27080832",
            osmType: OSM_TYPE_WAY,
            address: "Hoboken University Medical Center, 308, Willow Avenue, Downtown, Hoboken, Hudson County, New Jersey, 07030, United States",
            latitude: 40.741482500000004,
            longitude: -74.03397040924716,
        },
        reviews: [],
    },
    hobokenTrainStation: {
        _id: new ObjectId(),
        name: "NJ Transit Hoboken Train Station",
        description: "NJ Transit train station in Hoboken",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "7024801771",
            osmType: OSM_TYPE_NODE,
            address: "Hoboken Terminal, Warrington Plaza, Downtown, Hoboken, Hudson County, New Jersey, 07030, United States",
            latitude: 40.7349447,
            longitude: -74.0273829,
        },
        reviews: [],
    },
    ninthStreetLightRail: {
        _id: new ObjectId(),
        name: "9th Street NJ Transit HBLR Station",
        description: "NJ Transit Hudson-Bergen Light Rail Station at 9th Street",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "7681854809",
            osmType: OSM_TYPE_NODE,
            address: "9th Street-Congress Street, Jackson Street, Hoboken, Hudson County, New Jersey, 10017, United States",
            latitude: 40.7487251,
            longitude: -74.0386637,
        },
        reviews: [],
    },
    newarkAirport: {
        _id: new ObjectId(),
        name: "Newark Liberty International Airport",
        description: "International EWR Airport - Newark Liberty",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "141207228",
            osmType: OSM_TYPE_WAY,
            address: "Newark Liberty International Airport, US 1-9 Local, Newark, Essex County, New Jersey, 07114, United States",
            latitude: 40.68906405,
            longitude: -74.17725485035348,
        },
        reviews: [],
    },
    maristCollege: {
        _id: new ObjectId(),
        name: "Marist College",
        description: "Private college in Poughkeepsie, NY",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "14077708",
            osmType: OSM_TYPE_RELATION,
            address: "Marist College, Poplar Street, Fairview, Town of Poughkeepsie, Dutchess County, New York, 12601, United States",
            latitude: 41.722007000000005,
            longitude: -73.93438356318902,
        },
        reviews: [],
    },
    kingsVerona: {
        _id: new ObjectId(),
        name: "Kings Food Market",
        description: "Upscale American food market chain",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "857949885",
            osmType: OSM_TYPE_NODE,
            address: "Kings, 265-345, Pompton Avenue, Verona, Essex County, New Jersey, 07044, United States",
            latitude: 40.8338064,
            longitude: -74.2256087,
        },
        reviews: [],
    },
    kingsHoboken: {
        _id: new ObjectId(),
        name: "Kings Food Market",
        description: "Upscale American food market chain",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "4788723924",
            osmType: OSM_TYPE_NODE,
            address: "Kings Food Markets, Hudson Street, Uptown, Hoboken, Hudson County, New Jersey, 07030, United States",
            latitude: 40.7517055,
            longitude: -74.0251939,
        },
        reviews: [],
    },
    kingsMillburn: {
        _id: new ObjectId(),
        name: "Kings Food Market",
        description: "Upscale American food market chain",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "1015998401",
            osmType: OSM_TYPE_WAY,
            address: "Kings, Morris Turnpike, Short Hills, Millburn, Essex County, New Jersey, 07078, United States",
            latitude: 40.72243455,
            longitude: -74.33439192391381,
        },
        reviews: [],
    },
    sinatraParkHoboken: {
        _id: new ObjectId(),
        name: "Sinatra Park",
        description: "Small park featuring an outdoor amphitheater, soccer field, and a kayak launch with a view of New York City",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "24404351",
            osmType: OSM_TYPE_WAY,
            address: "Sinatra Park, Downtown, Hoboken, Hudson County, New Jersey, United States",
            latitude: 40.7411793,
            longitude: -74.02634826593933,
        },
        reviews: [],
    },
    pierCParkHoboken: {
        _id: new ObjectId(),
        name: "Pier C Park",
        description: "This park with scenic views of NYC features a fishing pier, playground, water play area & promenade.",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "10831115",
            osmType: OSM_TYPE_RELATION,
            address: "Pier C Park, Downtown, Hoboken, Hudson County, New Jersey, United States",
            latitude: 40.7401825,
            longitude: -74.02576306969146,
        },
        reviews: [],
    },
    pierAParkHoboken: {
        _id: new ObjectId(),
        name: "Pier A Park",
        description: "Park with scenic views of NYC in downtown Hoboken",
        comments: [],
        location: {
            _id: new ObjectId(),
            osmId: "24404263",
            osmType: OSM_TYPE_WAY,
            address: "Pier A Park, Downtown, Hoboken, Hudson County, New Jersey, United States",
            latitude: 40.73687525,
            longitude: -74.0262606326309,
        },
        reviews: [],
    }
}
